### ISSUE TITLE
Data not available for sugar content

### ISSUE THREAD

**Issue by divya9118** [cogsys-tuebingen/deephs_fruit#11]
Although code is written for estimating sugar content, and in paper it is also mentioned about sugar content. BUt in annotations.zip labels are not there. How can I get labels for sweetness.

**Comment by leonvarga** [comment]
Hi Divyani,

I fixed the annotations files. You can find them here: 
https://github.com/cogsys-tuebingen/deephs_fruit/tree/master/dataset

Honestly, we never used the json files for our experiments. We used the annotations within the python code, which are also used to create the json files. There was a bug in the generation process of the json-files. 

If you need another configuration. You can create the json files with the `core/fruit_list.py` file.

Keep in mind, there are no sugar values for the avocados.

Best regards and good luck,
Leon

**Comment by divya9118** [comment]
Even the annotations.zip file which is present at this location...does not ha sugar content updated in it. I request you to update the annotations.zip here. 
https://cogsys.cs.uni-tuebingen.de/webprojects/DeepHS-Fruit-2023-Datasets/

**Comment by leonvarga** [comment]
The updated file was updated...
[https://cogsys.cs.uni-tuebingen.de/webprojects/DeepHS-Fruit-2023-Datasets/annotations-upd-2024-01-09.zip](https://cogsys.cs.uni-tuebingen.de/webprojects/DeepHS-Fruit-2023-Datasets/annotations-upd-2024-01-09.zip)
