### ISSUE TITLE
Why are there not enough labels in the train_all_v2.json file?

### ISSUE THREAD

**Issue by Pongsan2540** [cogsys-tuebingen/deephs_fruit#14]
I loaded the dataset file name: Mango.zip and I am creating labels (file name : train_all_v2.json) for Mango data, but I found that the number of data records is greater than the specified number of labels. I checked the id in the records section and matched it with the id_ record_id in the annotations section, found that many records could not find matching labels.

For example: 
{"id": 3191, "fruit": "Mango", "side": "front", "day": "day_1_m3", "camera_type": "VIS", "files": {"header_file": "Mango/VIS/day_1_m3/mango_day_1_m3_01_front.hdr", "data_file": "Mango/VIS/day_1_m3/mango_day_1_m3_01_front.bin"}} 
I can't find the labels of this data json.

So I'm wondering if something went wrong.

**Comment by leonvarga** [comment]
I am not sure, whether I can follow your question fully. 

'train_all_v2.json' contains all available files. Also, the files of the test and validation set, but these without a label.

If you are only interested in the labeled trainings set files, you can use 'train_only_labeled_v2.json' or just ignore the entries without label.

**Comment by Pongsan2540** [comment]
@leonvarga  

I am facing the problem of not having enough labels in the file, just train_all_v2.json.

I would like to ask what could be the cause of the problem of incomplete labels? I've tried checking it out. I see that we have a total of 5307 data records, but the number of labels is only 636. 

I feel sorry for the 4,000 pieces of information that are unusable So I wonder what the cause is.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ADMIN/AppData/Local/Packages/oice_16_974fa576_32c1d314_2584/AC/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ADMIN/AppData/Local/Packages/oice_16_974fa576_32c1d314_2584/AC/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


fruit | side | camera_type | count | Check math
-- | -- | -- | -- | --
Avocado | front | NIR | 159 | 18
Avocado | back | NIR | 163 | 22
Avocado | front | VIS | 466 | 46
Avocado | back | VIS | 466 | 46
Avocado | front | VIS_COR | 132 | 0
Avocado | back | VIS_COR | 132 | 0
Kiwi | front | NIR | 180 | 29
Kiwi | back | NIR | 180 | 29
Kiwi | front | VIS | 551 | 72
Kiwi | back | VIS | 545 | 66
Kiwi | front | VIS_COR | 0 | 0
Kiwi | back | VIS_COR | 0 | 0
Kaki | front | NIR | 0 | 0
Kaki | back | NIR | 0 | 0
Kaki | front | VIS | 182 | 24
Kaki | back | VIS | 189 | 32
Kaki | front | VIS_COR | 186 | 27
Kaki | back | VIS_COR | 188 | 29
Mango | front | NIR | 0 | 0
Mango | back | NIR | 0 | 0
Mango | front | VIS | 268 | 27
Mango | back | VIS | 270 | 29
Mango | front | VIS_COR | 268 | 27
Mango | back | VIS_COR | 270 | 29
Papaya | front | NIR | 0 | 0
Papaya | back | NIR | 0 | 0
Papaya | front | VIS | 130 | 23
Papaya | back | VIS | 126 | 19
Papaya | front | VIS_COR | 130 | 23
Papaya | back | VIS_COR | 126 | 19
  |   | SUM | 5307 | 636



</body>

</html>


[check_train_all_v2.xlsx](https://github.com/user-attachments/files/16033748/check_train_all_v2.xlsx)
[train_all_v2.json](https://github.com/user-attachments/files/16033578/train_all_v2.json)

**Comment by leonvarga** [comment]
As mentioned in the corresponding paper, not all recordings were labeled. 
The measurement is a destructive measurement and therefore only a subset was labeled.

The unlabeled recordings can be used for unsupervised techniques like self-supervised learning.


If you are interested only in the labeled recordings, use the file:  train_only_labeled_v2.json

**Comment by Pongsan2540** [comment]
Thank you very much. Your answer helped me a lot.
