### ISSUE TITLE
Dataset link does not work

### ISSUE THREAD

**Issue by behnazeslami** [cogsys-tuebingen/deephs_fruit#2]
Hi,

I would like to download the dataset through this link: https://cloud.cs.uni-tuebingen.de/index.php/s/nWKxxtN5wM9fz5E you have mentioned in the README section. Unfortunately, it does not work. If possible, please guide me to download dataset V2.

Thanks!

**Comment by leonvarga** [comment]
Fixed :-)

**Comment by phamtronglam** [comment]
Hi @leonvarga 

The URL in next cloud is EXTREMELY SLOW. I waited 10 minutes and it still could not load (tried for 2 days). Could you please upload the dataset to another server, please?
