### ISSUE TITLE
Dataset link is EXTREMELY SLOW and cannot load

### ISSUE THREAD

**Issue by phamtronglam** [cogsys-tuebingen/deephs_fruit#3]
Hi @leonvarga

The URL in next cloud is EXTREMELY SLOW. I waited 10 minutes and it still could not load (tried for 2 days). Could you please upload the dataset to another server, please?

**Comment by leonvarga** [comment]
Hi @phamtronglam,

Thank you for your request.

I checked the link five minutes ago and it worked fine for me. The download started within seconds. 

So, I think it is not a problem of the server itself. I see two possible problems:
- Where are you from? Maybe the connection to Germany is the problem.
- Maybe it is only a visualization problem. Could you please check another browser?

As the data set has over 200GB, it is not easy to find a second mirror for the data. I will check, whether we can provide a torrent download, but this takes time until end of next week.

Best regards
Leon

Send via smartphone

**Comment by phamtronglam** [comment]
Thank you @leonvarga for your quick reply and suggestions.

I'm from Japan and behind a company proxy (disclaimer: I do not know much about network stuff).
On the computer where I could turn off the proxy for a short time for testing, the next cloud sever loaded very quickly and so did the download. Unfortunately, transfering 200 GB from this computer to the main computer where I work (and the one I cannot turn off the proxy) is not possible.
I am tweaking the proxy settings and the server UI could load fairly quickly, however the download is still problematic (download of Annotations ~ several MB was OK, but the loading of download of other larger files ( > several GB) was very slow and turned into error before the actual download could have started).

I understand that a free server for 200GB is not a trivial task. If possible, torrent is still wanted. I'm sorry to trouble you.

**Comment by leonvarga** [comment]
I think the proxy is slowing down your network connection. As a result, the torrent will not speed up your download.

Still, I will try to provide a torrent in the next week.

Greetings

**Comment by phamtronglam** [comment]
Thank you very much. I'm looking forward for the torrent link.

Bests,

**Comment by leonvarga** [comment]
The torrent link takes more time than expected. Can you still continue your work?

**Comment by phamtronglam** [comment]
Thank you for your concern. I can wait.

**Comment by leonvarga** [comment]
You can find a direct download and a torrent-file here: https://cogsys.cs.uni-tuebingen.de/webprojects/Deepths-Fruits-2023-Datasets/

Best regards
Leon

**Comment by phamtronglam** [comment]
Hi Leon,

Thank you very much for your dedication.
I'm now downloading from the direct link you provided.

Bests,
Lam
