### ISSUE TITLE
dataset is corrupted?

### ISSUE THREAD

**Issue by Slieee** [cogsys-tuebingen/deephs_fruit#4]
Hello, I'm just a beginner and I needed this dataset. I tried to download just one dataset HSI(avocado specifically)just to test it out but every time I try to open, it says it's either corrupted or invalid. Is it possible for you to give me advice on what I might did wrong(e.g wrong app). it's quite urgent so I appreciate a quick reply. Thank you.

**Comment by leonvarga** [comment]
Hey Slieee,
Welcome! 
It is quite hard to give you advice without more details.
Which tool are you using to extract the zip-file? I think every Unzip-tool should work here, because we do not use any special encryption.

Further, could you please check, whether the download is complete and was not interrupted as the files are quite large.
For test purpose, you could for example download the Kaki subfolder, which is only 3GB large. If you can extract this, I think your previous download is maybe broken.

Best regards,
Leon

**Comment by Slieee** [comment]
Hello Leon,
First of all, thank you for the fast reply, you even replied when I sleep. 
I use WinRaR as the zip file extractor, and I will also take your advice and try the kaki subfolder first.  

Again, I'm quite grateful for your reply and I wish all the blessings in the world. I will try again and update if there is any problem.

**Comment by leonvarga** [comment]
There is a second download-mirror, also with a torrent-option, available: https://cogsys.cs.uni-tuebingen.de/webprojects/Deepths-Fruits-2023-Datasets/

**Comment by Slieee** [comment]
Thank you Mr Leon. 
I'm actually not in this range of study, but I am quite interested in Machine Learning. I can't quite figure out how to run the code as it is my first time, can you advice me on that also? for example, what app do you use for this program in particular, how do you arrange the code file in ide, as my ide can't seem to read the imports unless it is the file above it and if there are any hardware requirement to run the code. if you are willing, I can email you privately and give you more detail about my problem.

**Comment by leonvarga** [comment]
Hi Sliee,

Thank you for reaching out! I'd be happy to help you with your question.

Firstly, the code is written in Python 3.10, so it's important to have a good understanding of Python. Additionally, two main libraries are utilized: PyTorch (https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html) and PyTorch-Lightning (https://www.pytorchlightning.ai/tutorials). PyTorch is a widely used deep-learning framework, while PyTorch-Lightning helps structure the code and eliminates boilerplate code.

It's worth noting that a basic understanding of Python and PyTorch is essential to comprehend the code effectively.

You can run the code on a regular desktop computer with approximately 16 GB of RAM and 300 GB of disk space. However, for improved performance during inference and training, I recommend utilizing a CUDA-compatible GPU. You can find more information about GPU usage with PyTorch at https://pytorch.org/get-started/locally/.

If you have any further questions or need assistance, feel free to ask.

Best regards,
Leon

**Comment by Slieee** [comment]
Hi Mr Leon, 
my only available device is a laptop with 16GB RAM(15.7 RAM available) and 474GB SSD disk space. My processor is 12th Gen Intel(R) Core(TM) i5-1235U  1.30 GHz. Can I run the code with these features? 

p.s I also use PyCharm IDE with 3.11 Python interpreter.

**Comment by leonvarga** [comment]
That works well.
PyCharm is also a good option. (Before switching to NeoVim, I used PyCharm :-)). To add a project, go to File -> Open and select the root folder of the git repository. Then, configure your Python launcher. The main file for normal training is classification/train.py. When you execute this file, it will display the necessary parameters that you can define within the run configuration.
Best regards,
Leon

**Comment by Slieee** [comment]
Thank you for the advice Mr Leon,
I set up a virtual environment with Python 3.10, I was unable to install the h5py ver 2.10 so install the latest version 3.9.0. I tried to run the classification\train.py using the command 
"python C:\Users\User\PycharmProjects\deephs_fruit\classification\train.py --data_path c:\Users\Documents\FYP\dataset --model deephs_net --fruit avocado --classification_type ripeness --seed23312323" 
but an error occured 
"from classification.model_factory import get_model, VALID_MODELS, CAMERA_AGNOSTIC_MODELS
ModuleNotFoundError: No module named 'classification'"
I have no idea what's causing the problem and why it cannot find the module in the file. Since you use Pycharm before, I wanted to know if you have any solution or advice that you think might fix this problem?

**Comment by leonvarga** [comment]
Hi Slieee,

it seems like the Python-interpreter is not finding the classification folder. Could you please check whether the working directory of your configuration is also the root-directory of the GitHub project?

I start the projects normally within the root-directory of the project and add the current directory to the PYTHONPATH. This also allows python to load the dependency within this folder. Like:
PYTHONPATH=$PYTHONPATH:. python classification\train.py --data_path [path-to-data-set] --model deephs_net --fruit avocado --classification_type ripeness --seed 23312323

In PyCharm you have to do this implicit by using the working-directory or explicit by marking the folder as source root.

I hope thats somehow clear :-)
Good luck

Best regards
Leon
