### ISSUE TITLE
Error on installing h5py

### ISSUE THREAD

**Issue by phamtronglam** [cogsys-tuebingen/deephs_fruit#5]
When I tried to create a new conda environment and use pip install -r requirements.txt, I got this error.

`  error: Could not find module 'hdf5.dll' (or one of its dependencies). Try using the full path with constructor syntax.`

I resolved it by using
`pip install h5py --only-binary h5py
`
https://github.com/h5py/h5py/issues/2146

I'm using Windows 10 x64.

Hope this is useful for some one.

Regards,
Lam

**Comment by leonvarga** [comment]
Thank you for pointing this out!
