### ISSUE TITLE
cannot run training code on Windows

### ISSUE THREAD

**Issue by phamtronglam** [cogsys-tuebingen/deephs_fruit#6]
Dear @leonvarga 

Thank you for uploading the direct download link for dataset last time.
I'm now trying to run the training code.

Unfortunately, I encountered the following error. I'm not sure what it points to and have no idea since your code used a module core which I think is related to PBS, but I'm running a windows machine with 2 different GPUs.

Do you have any idea how to fix this?

`(HSI_deep_fruit) D:\tmp\HSI\deephs_fruit>python classification/train.py --data_path ../dataset --model deephs_net --fruit avocado --classification_type ripeness --seed 23312323
Global seed set to 23312323
Hparams: {'model': 'deephs_net', 'batch_size': 64, 'lr': 0.01, 'fruit': <Fruit.AVOCADO: 'Avocado'>, 'camera_type': <CameraType.VIS: 'VIS'>, 'classification_type': <ClassificationType.RIPENESS: 'ripeness'>, 'num_epochs': 5000, 'data_path': '../dataset', 'seed': 23312323, 'log_path': None, 'online_logging': False, 'debug': False, 'model_checkpoint': None, 'comment': None, 'camera_agnostic_num_gauss': 5, 'hidden_layers': [25, 30, 50], 'type': 'single_camera', 'git_id': '3a4d7075d2823aceb37b8e6b2919e30d302a53cf', 'slurm_job_id': 'WUDL1329:D:\\tmp\\HSI\\deephs_fruit', 'slurm_job_path': '', 'num_workers': 4, 'bands': 224, 'wavelengths': [397.66, 400.28, 402.9, 405.52, 408.13, 410.75, 413.37, 416.0, 418.62, 421.24, 423.86, 426.49, 429.12, 431.74, 434.37, 437.0, 439.63, 442.26, 444.89, 447.52, 450.16, 452.79, 455.43, 458.06, 460.7, 463.34, 465.98, 468.62, 471.26, 473.9, 476.54, 479.18, 481.83, 484.47, 487.12, 489.77, 492.42, 495.07, 497.72, 500.37, 503.02, 505.67, 508.32, 510.98, 513.63, 516.29, 518.95, 521.61, 524.27, 526.93, 529.59, 532.25, 534.91, 537.57, 540.24, 542.91, 545.57, 548.24, 550.91, 553.58, 556.25, 558.92, 561.59, 564.26, 566.94, 569.61, 572.29, 574.96, 577.64, 580.32, 583.0, 585.68, 588.36, 591.04, 593.73, 596.41, 599.1, 601.78, 604.47, 607.16, 609.85, 612.53, 615.23, 617.92, 620.61, 623.3, 626.0, 628.69, 631.39, 634.08, 636.78, 639.48, 642.18, 644.88, 647.58, 650.29, 652.99, 655.69, 658.4, 661.1, 663.81, 666.52, 669.23, 671.94, 674.65, 677.36, 680.07, 682.79, 685.5, 688.22, 690.93, 693.65, 696.37, 699.09, 701.81, 704.53, 707.25, 709.97, 712.7, 715.42, 718.15, 720.87, 723.6, 726.33, 729.06, 731.79, 734.52, 737.25, 739.98, 742.72, 745.45, 748.19, 750.93, 753.66, 756.4, 759.14, 761.88, 764.62, 767.36, 770.11, 772.85, 775.6, 778.34, 781.09, 783.84, 786.58, 789.33, 792.08, 794.84, 797.59, 800.34, 803.1, 805.85, 808.61, 811.36, 814.12, 816.88, 819.64, 822.4, 825.16, 827.92, 830.69, 833.45, 836.22, 838.98, 841.75, 844.52, 847.29, 850.06, 852.83, 855.6, 858.37, 861.14, 863.92, 866.69, 869.47, 872.25, 875.03, 877.8, 880.58, 883.37, 886.15, 888.93, 891.71, 894.5, 897.28, 900.07, 902.86, 905.64, 908.43, 911.22, 914.02, 916.81, 919.6, 922.39, 925.19, 927.98, 930.78, 933.58, 936.38, 939.18, 941.98, 944.78, 947.58, 950.38, 953.19, 955.99, 958.8, 961.6, 964.41, 967.22, 970.03, 972.84, 975.65, 978.46, 981.27, 984.09, 986.9, 989.72, 992.54, 995.35, 998.17, 1000.99, 1003.81], 'augmentation_config': {'random_flip': True, 'random_rotate': True, 'random_noise': False, 'random_cut': True, 'random_crop': True, 'random_intensity_scale': False}, 'test_augmentation': True, 'tta_augmentation_config': {'random_flip': True, 'random_rotate': True, 'random_noise': False, 'random_cut': False, 'random_crop': False, 'random_intensity_scale': False}, 'tta_augmentation_iterations': 5, 'num_classes': 3, 'input_size': (64, 64)}
Traceback (most recent call last):
  File "D:\tmp\HSI\deephs_fruit\classification\train.py", line 422, in <module>
    main(hparams)
  File "D:\tmp\HSI\deephs_fruit\classification\train.py", line 366, in main
    logger = WandbLogger(offline=not hparams['online_logging'], save_dir=hparams['log_path'],
  File "D:\miniconda3_windows\envs\HSI_deep_fruit\lib\site-packages\pytorch_lightning\loggers\wandb.py", line 303, in __init__
    dir=save_dir or kwargs.pop("dir"),
KeyError: 'dir'`

Thanks a lot.
Lam

**Comment by leonvarga** [comment]
Hello Lam,

I hope this message finds you well. It's important to note that the code hasn't been tested on the Windows platform, so there might be unforeseen issues that arise as you proceed. One potential area of concern is our filename handling, which could present challenges.

The error you've shared seems to be related to the WandB package. To better assist you, could you please specify the version of wandb that you are currently using?

Regarding the "core" module you mentioned, it resides within the project and can be found in the root folder. To ensure its accessibility, it's necessary to add the root folder to your PYTHONPATH. For Windows, this process is a bit more involved, as outlined in this StackOverflow thread: [link](https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-so-it-finds-my-modules-packages). On Linux, this task is simpler. You might want to attempt adding a relative '.' to the PYTHONPATH and running the code from the root folder to see if that resolves the 'core' issue.

I apologize for any inconvenience this may cause, as our development environment primarily revolves around Linux. 

Best regards,
Leon

**Comment by phamtronglam** [comment]
Hi Leon,

Thank you for your kind message.
I understand that maintaining codes is not an easy task, and it is very difficult to troubleshoot another system that is different from the developer environment. Don't be discouraged.

I will try again on WSL to see if there is anything more promising.

FYI, my wandb version is wandb   0.13.3, which is the same with requirements.txt. I know how to setup environment variable PYTHONPATH in windows. 

I'll update with my try on WSL.

Many thanks,
Lam

**Comment by phamtronglam** [comment]
Hi Leon,

I tried on WSL but the same error message about 'dir' keyError appeared.
Here is the environment for my windows and WSL.

I just post here for future reference, if the debug seems time consuming, I will just leave it as it is now.

[WSL_deep_fruit.txt](https://github.com/cogsys-tuebingen/deephs_fruit/files/12374936/WSL_deep_fruit.txt)
[windows_deep_fruit.txt](https://github.com/cogsys-tuebingen/deephs_fruit/files/12374937/windows_deep_fruit.txt)

**Comment by stdio159** [comment]
I also met your problem. How did you solve the problem? Thank you.

**Comment by phamtronglam** [comment]
Hi, 

Unfortunately I was not able to resolve the problem. 
My suggestion is that you try using a real Ubuntu installation or use a virtual machine.
