### ISSUE TITLE
Dataset unavailable

### ISSUE THREAD

**Issue by YeisonJimenez** [cogsys-tuebingen/deephs_fruit#7]
Hello Leon, the dataset is not available for download.

**Comment by YeisonJimenez** [comment]
@leonvarga the download link shows 404 error, file not found.

**Comment by leonvarga** [comment]
Hey @YeisonJimenez,

Yesterday, we moved the files to a new server. Sorry for the inconvenience.

The new link is: https://cogsys.cs.uni-tuebingen.de/webprojects/DeepHS-Fruit-2023-Datasets/

Best regards,
Leon Varga

**Comment by YeisonJimenez** [comment]
Thank you so much!
